name: Run Jest tests

on:
  pull_request:
    branches:
    - main
    
  push:
    branches:
      -main

jobs:
  jestTest:
    runs-on: macos-latest
    env:
      URL: ${{ secrets.URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm i
      - run: npm test
